version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/CryptoArbitrage
hooks:
  BeforeInstall:
    - location: deploy/AwsCodeDeployScript.sh
      timeout: 300
  AfterInstall:
    - location: deploy/AwsCodeDeployScript.sh
      timeout: 300
  ApplicationStart:
    - location: deploy/AwsCodeDeployScript.sh
      timeout: 300