FROM ubuntu:16.04
RUN apt-get update && apt-get install -y locales software-properties-common \
 && rm -rf /var/lib/apt/lists/* \
 && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
ADD https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.13.tgz .
RUN tar -zxvf mongodb-linux-x86_64-3.0.13.tgz \
 && cp -R -n mongodb-linux-x86_64-3.0.13/bin/* /usr/bin/ \
# Install PHP and dependencies:
 && apt-get update \
 && apt-get install -y php7.0-cli php7.0-dev php7.0-curl php7.0-xml php7.0-bcmath php7.0-mbstring pkg-config \
# Setup mbstring function overload for all str functions to use mb_ variants
 && echo "mbstring.func_overload 7" >> /etc/php/7.0/cli/php.ini \
 && echo "mbstring.language Neutral" >> /etc/php/7.0/cli/php.ini \
# Pecl setup
 && pecl config-set php_ini /etc/php/7.0/cli/php.ini \
# Install PHP mongo libs
 && pecl install mongodb \
 && echo "extension=mongodb.so" >> /etc/php/7.0/mods-available/mongodb.ini \
 && ln -s -T /etc/php/7.0/mods-available/mongodb.ini /etc/php/7.0/cli/conf.d/99-mongodb.ini \
# Install Composer for mongodb lib
 && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
 && php composer-setup.php --quiet --install-dir=/usr/bin --filename=composer \
# Install log4php, pear reports error on install if package already exists
 && apt-get install -y php-pear \
 && pear channel-discover pear.apache.org/log4php \
 && pear install log4php/Apache_log4php \
 && apt-get install -y phpunit
RUN mkdir -p /data/db
ENTRYPOINT ["/CryptoArbitrage/deploy/docker_start.sh"]
